modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mixins]]
config = "${mod_id}.mixins.json"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "KRender Model Loading"
authors = "Kneelawk"
description = "Cross-platform Model Loader."
logoFile = "assets/${mod_id}/icon.png"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "REQUIRED"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"
