modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "KRender Engine NeoForge Backend"
authors = "Kneelawk"
description = "NeoForge Backend for the KRender Engine."
logoFile = "assets/${mod_id}/icon.png"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "REQUIRED"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "krender_engine_api"
type = "REQUIRED"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "common_events"
type = "REQUIRED"
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"
