name: prerelease

env:
  PROJECT_NAME: KRender
  JAVADOC_DIR: com/kneelawk/krender/krender-javadoc-xplat
  MAVEN_IDENTIFIER: 'com.kneelawk.krender:krender-engine-api-xplat-intermediary'
  ROLE_ID: '1239439830979710988'

on:
  push:
    tags:
      # matches things like v0.1.2-alpha.1+1.18.2
      - 'v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+\+[0-9]+.[0-9]+.[0-9]+'
      # matches things like v0.1.2-beta.1+1.18.2
      - 'v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+\+[0-9]+.[0-9]+.[0-9]+'
      # matches things like v0.1.2-pre.1+1.18.2
      - 'v[0-9]+.[0-9]+.[0-9]+-pre.[0-9]+\+[0-9]+.[0-9]+.[0-9]+'
      # matches things like v0.3.0-alpha.1+1.19
      - 'v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+\+[0-9]+.[0-9]+'
      # matches things like v0.3.0-beta.1+1.19
      - 'v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+\+[0-9]+.[0-9]+'
      # matches things like v0.3.0-pre.1+1.19
      - 'v[0-9]+.[0-9]+.[0-9]+-pre.[0-9]+\+[0-9]+.[0-9]+'

jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build
        env:
          RELEASE_TAG: ${{ github.ref_name }}
      - name: Github Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
      - name: Maven Release
        run: ./gradlew publish -PkneelawkUsername=${{ secrets.MAVEN_USERNAME }} -PkneelawkPassword=${{ secrets.MAVEN_PASSWORD }}
        env:
          RELEASE_TAG: ${{ github.ref_name }}
      # This is the mess that publishes discord notifications
      - name: Process for Announcement
        uses: actions/github-script@v7
        id: announcement_text
        env:
          TAG_VERSION: ${{ github.ref_name }}
        with:
          script: |
            let fullVersion = process.env.TAG_VERSION;
            let versions = fullVersion.split('+');
            let mavenVersion = fullVersion.substring(1);
            let lines = [];
            lines.push(`# ${process.env.PROJECT_NAME} Prerelease`);
            lines.push(`**<@&${process.env.ROLE_ID}> ${process.env.PROJECT_NAME} prerelease ${versions[0]} has been published for Minecraft ${versions[1]}!**`);
            lines.push("Available on Kneelawk's maven: https://maven.kneelawk.com/releases/", `With the identifier: \`${process.env.MAVEN_IDENTIFIER}:${mavenVersion}\``);
            lines.push(`Javadoc available at: https://maven.kneelawk.com/javadoc/releases/${process.env.JAVADOC_DIR}/${mavenVersion}`);
            return lines.join('\n');
          result-encoding: string
      - name: Make Release Announcement
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: ${{ steps.announcement_text.outputs.result }}
